update mesa experiment 'beta-eddington'

diff --git a/radiation/beta-eddington/re b/radiation/beta-eddington/re
--- a/radiation/beta-eddington/re
+++ b/radiation/beta-eddington/re
@@ -1,21 +1,31 @@
 #!/bin/bash
 
-function check_okay {
-	if [ $? -ne 0 ]
-	then
-		exit 1
-	fi
+photo_directory=photos
+
+function most_recent_photo {
+    ls -t "$photo_directory" | head -1
 }
 
-case $1 in
-    1) cp inlist_1M inlist;;
-    3) cp inlist_3M inlist;;
-    10) cp inlist_10M inlist;;
-    30) cp inlist_30M inlist;;
-    *) echo "unknown mass"; exit 1;;
-esac
+if [ $# -eq 0 ]
+then
+    photo=$(most_recent_photo)
+else
+    photo=$1
+fi
 
-echo $2
-cp ZAMS_${1}M/photos/$2 restart_photo
-check_okay
-date;./star;date
+if [ -z "$photo" ] || ! [ -f "$photo_directory/$photo" ]
+then
+    echo "specified photo does not exist"
+    exit 1
+fi
+
+echo "restart from $photo"
+if ! cp "$photo_directory/$photo" restart_photo
+then
+    echo "failed to copy photo"
+    exit 1
+fi
+
+date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
+./star
+date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
diff --git a/radiation/beta-eddington/rn b/radiation/beta-eddington/rn
--- a/radiation/beta-eddington/rn
+++ b/radiation/beta-eddington/rn
@@ -1,17 +1,27 @@
 #!/bin/bash
 
-if [ ! -z "${MESA_DIR}" ]; then
-  svn info $MESA_DIR > .svninfo
-  grep "Revision" .svninfo
-fi
+function do_one {
+    INLIST="inlist_${1}_header"
+    if [ ! -e "${INLIST}" ]
+    then
+        echo "target inlist file ${INLIST} does not exist"
+        exit 1
+    fi
+    cp "${INLIST}" inlist
+    echo 'run' "$1"
+    if ! ./rn1
+    then
+        echo "rn1 failed"
+        exit 1
+    fi
+    echo
+    echo "finished $1"
+    echo
+}
 
-case $1 in
-    1) cp inlist_1M inlist;;
-    3) cp inlist_3M inlist;;
-    10) cp inlist_10M inlist;;
-    30) cp inlist_30M inlist;;
-    *) echo "unknown mass"; exit 1;;
-esac
+for m in 1 3 10 30
+do
+    do_one ${m}M
+done
 
-rm -f restart_photo
-date;./star;date
+echo 'finished'
